import { Button, VerticalBox, GridBox, LineEdit, Slider, ScrollView } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();

    GridLayout {
        padding: 25px;
        spacing: 15px;

        Row{
            Text {
                text: "Rust Music Player";
                horizontal-alignment: center;
                font-size: 45px;
            }
        }

        HorizontalLayout {
            VerticalBox {
                alignment: start;
                    Button {
                        text: "Home";
                        width: 150px;
                    }
        
                    Button {
                        text: "Libary";
                        width: 150px;
                    }
            }
    
            ScrollView {
                width: 400px;
                height: 250px;
                
                Rectangle {
                    width: 100%;  
                    height: 100%; 
                    background: Colors.darkgrey;
                }
                
                VerticalLayout {
                    alignment: center;
                    Text {
                        text: "About This Project";
                        font-size: 20px;
                    }
                    
                    Text {
                        text: "This project was made as a school project, written in Rust and Slint. In this project I studied Rust and how it can be used.";
                    }
                }
            }
        }

        Row{
            HorizontalLayout {
                alignment: center;
                Button {
                    text: "Back";
                    width: 100px;
                }
                Button {
                    text: "Play";
                    width: 100px;
                }
                Button {
                    text: "Next";
                    width: 100px;
                }
            }
        }

        Row {

            HorizontalLayout {
                spacing: 20px;
                Text{
                    horizontal-alignment: center;
                    text: "00:00";
                    font-size: 18px;
                    font-weight: 100;
                }

                Slider {
                    width: 800px;
                    height: 15px;
                    value: 0;
                }

                Text{
                    horizontal-alignment: center;
                    text: "00:00";
                    font-size: 18px;
                    font-weight: 100;
                }

            }
        }
    }
}
