import { Button, VerticalBox, GridBox, LineEdit, Slider, ScrollView } from "std-widgets.slint";

export component AppWindow inherits Window {
    property<bool> is_home_page: true; 

    callback home-clicked();
    callback library-clicked();

    GridLayout {
        padding: 25px;
        spacing: 15px;

        Row {
            Text {
                text: "Rust Music Player";
                font-family: "Calibri";
                horizontal-alignment: center;
                font-size: 45px;
            }
        }

        HorizontalLayout {
            VerticalBox {
                alignment: start;
                Button {
                    text: "Home";
                    width: 150px;
                    clicked => {
                        root.is_home_page = true;
                        root.home-clicked();
                    }
                }

                Button {
                    text: "Library";
                    width: 150px;
                    clicked => {
                        root.is_home_page = false;
                        root.library-clicked();
                    }
                }
            }

            ScrollView {
                width: 700px;
                height: 350px;

                Rectangle {
                    width: 100%;
                    height: 100%;
                    background: #212121;
                }

                VerticalLayout {
                    alignment: start;
                    padding: 15px;
                    // Show the home page content if is_home_page is true
                    Text {
                        text: "Home Page";
                        font-size: 30px;
                        visible: root.is_home_page;
                    }
                    
                    // Show the library page content if is_home_page is false
                    Text {
                        text: "Library Page";
                        font-size: 30px;
                        visible: !root.is_home_page;
                    }
                }
            }
        }
    }
}
